#!/usr/bin/env bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

# Start the Nginx service
sudo service nginx start

